### ISSUE TITLE
Challenge #23 -What is an optimal number of vertical model levels to represent atmospheric trace gases

### ISSUE THREAD

**Issue by EsperanzaCuartero** [esowc/challenges_2020#7]
# Challenge #23 - What is an optimal number of vertical model levels to represent atmospheric trace gases?  
> **Stream 2** - Machine-Learning and Artificial Intelligence

### Goal
Finding an optimal vertical resolution that requires a minimum number of vertical levels to represent the vertical structure of atmospheric traces gases (ozone, NO2, CO2, and aerosols), which are simulated by the ECMWF model on 137 model levels. Different scenarios should be represented for reduction of the model levels in the range between 70 to 10 model levels.

### Mentors and skills
* **Mentors:** @miha-at-ecmwf @JohannesFlemming
* **Skills required**
  * Spatial (3D) data analysis of large data set
  * Statistical analysis skills
  * Familiarity with the concept of the vertical discretization in meteorological models will be helpful but is not essential 
<hr>

#### Data  
CAMS operational forecast data for ozone, NO2, aerosols and CO2 at the original 137 model levels. 

#### What is the current problem/limitation?
The IFS uses 137 levels in the atmosphere to simulate the weather as well as transport and the sources and sinks of atmospheric trace gases. The traces gases tend to have pronounced vertical gradients predominately close to the surface and for ozone and NO2 also in the stratosphere. Far fewer than the 137 model level may be sufficient to represent the vertical variability of the trace gases. 

#### What could be the solution?
* Use data mining techniques to identify the areas of strong typical and episodical vertical variability in the CAMS data. These areas of gradient can vary for the different chemical species. 
* Define a set of useful evaluation metrics for the accuracy of the reduced model set. Scientific guidance will be given. 
* Find an optimal common subset of vertical models levels that provides the best cost (loo in accuracy) to benefit (data volume reduction) ratio valid for all species 

#### Further directions
Apply the method to also reduce the horizontal resolution in areas with little gradients such as over the ocean or int the stratosphere.

**Comment by JiaweiZhuang** [comment]
That's an interesting problem! My paper on ACP is quite relevant: [The importance of vertical resolution in the free troposphere for modeling intercontinental plumes](https://www.atmos-chem-phys.net/18/6039/2018/)

**Comment by JohannesFlemming** [comment]
Hi Jiawei,

thank you for your input. The optimal resolution for the model is indeed an interesting science questions. Your and
Sebastien Eastham's papers point out the importance of the a high vertical resolution for long-range plume transport. (It would be interesting to see if your findings are also valid for the semi-Lagrangian advection scheme of the IFS.)

The core of the  esowc is to find a cost effective resolution for the archiving of the data. The model IFS will continue to run the 137 vertical level configuration. NWP data are mostly stored on about 20 pressure levels. I want the project to find a good compromise between the NWP approach and archiving the full 137 levels all the time (which actually takes much longer than running the model).

Giving your research background, would you be interested to propose a solution  ?

kind regards,
Johannes

________________________________

**Comment by jwagemann** [comment]
Join us for our LIVE @ecmwf Summer of Weather Code Ask Me Anything session on 1 April 2020 at 2 pm (CET) (tomorrow).

Get infos first hand from the #ESoWC2020 organisers, mentors and former #ESoWC participants.
➡️[Sign up](https://esowc.ecmwf.int/ama)

**Comment by jwagemann** [comment]
Only 4 days left to apply to be part of ECMWF Summer of Weather Code 2020. 
Application deadline: **Wednesday, 22 April 2020 at 23:59 (BST)**. 
Submit your proposal [here](https://esowc.commpla.com/form/application-form).
