### ISSUE TITLE
Challenge #25 -Virtual assistant for users of ECMWF online products and services

### ISSUE THREAD

**Issue by EsperanzaCuartero** [esowc/challenges_2020#9]
# Challenge #25 - Virtual assistant for users of ECMWF online products and services  

> Stream 2 - Machine-Learning and Artificial Intelligence

### Goal
To reduce the number of questions which need answering in person. The AI should ‘converse’ with the user to guide users to what they need. 

### Mentors and skills:
* **Mentors:** @annaghelli @kiden @MichyG
* **Skills required**
  * Knowledge of [Dialog flow](https://dialogflow.com) or similar
  * Understanding of content (indexing, metadata, etc)
  * Confluence and Jira Service Desk and their APIs

<hr>

#### Data and systems to be used 
* [Dialog flow](https://dialogflow.com/) or similar (virtual assistant) 
* Confluence user doc space (current location of documentation and content to train the virtual assistant) 
* Jira Service Desk (current location of documentation and content to train the virtual assistant) 

 #### What is the current problem/limitation?*
We want create an effectiveness and efficient support service for our users. Currently answers to any support question require human resources independently from the complexity of the request.  

#### What could be the solution?
The idea is to move some of the basic queries to a self-serve service whereby users can answer their questions helped by a virtual assistant. The basic metadata to train the virtual assistant are available on an internal wiki and ticketing service (Confluence and JIRA service desk, part of the Atlassian suit).  
As an  example of the virtual assistant we propose [Dialog flow](https://dialogflow.com/) or similar.

**Comment by michiboo** [comment]
@kiden  @annaghelli  Hi, I am quite interested in this project! Is it possible to look at some sample of the basic metadata?

**Comment by annaghelli** [comment]
@michiboo great to hear you are interested. Will come back with more info Monday.

**Comment by kiden** [comment]
Hi @michiboo glad to hear you're interested! You can see a lot of the content we want the AI to work with at https://confluence.ecmwf.int/display/UDOC. At the moment it's mostly body content without much metadata, but we will restructure it and add more metadata ahead of and during the AI project. Get back to us if you have any more questions.

**Comment by annaghelli** [comment]
@michiboo you can find more details here: https://confluence.ecmwf.int/display/CKB/ 
this is our knowledge base. Content is tagged to improve searchability

If you want to know more, please get in touch and we can provide more details

**Comment by MichyG** [comment]
@michiboo the [Copernicus User Support Forum](https://confluence.ecmwf.int/display/CUSF/Copernicus+User+Support+Forum+Home) may also be of interest to you. It contains some of the questions frequently asked by our users.

Please let us know if you have any further questions.

**Comment by michiboo** [comment]
@MichyG  @annaghelli  @kiden  Thank you for the responses! I will post here if I have further questions

**Comment by michiboo** [comment]
In this challenge, do we need to consider integration of the chatbot/virtual assistant into the website?

**Comment by MichyG** [comment]
Hi, yes we would like to have a similar widget like in the [Copernicus Climate Change Service](https://climate.copernicus.eu/) website but more interactive.

**Comment by michiboo** [comment]
Hi, Is there a log.txt consist of questions that were asked by users available? It could be really useful.

**Comment by C3S-ULS** [comment]
We have a number of pages with F&Q which you can check, but they are not comprehensive of all the requests we get. We will be able to provide a more comprehensive list nearer to  the coding period. Some examples are here:
https://confluence.ecmwf.int/display/ECC/Frequently+Asked+Questions
https://confluence.ecmwf.int/display/UDOC/ecCodes+General+-+Frequently+Asked+Questions+-+FAQS
https://confluence.ecmwf.int/display/MAGP/Frequently+Asked+Questions+on+Magics
https://confluence.ecmwf.int/display/UDOC/ecFlow+Frequently+Asked+Questions+-+FAQs
https://confluence.ecmwf.int/display/UDOC/MARS+FAQ
https://confluence.ecmwf.int/display/TIGGE/FAQ
https://confluence.ecmwf.int/dosearchsite.action?queryString=cds&where=CKB

hope this can help you!

**Comment by jwagemann** [comment]
Join us for our LIVE @ecmwf Summer of Weather Code Ask Me Anything session on 1 April 2020 at 2 pm (CET) (tomorrow).

Get infos first hand from the #ESoWC2020 organisers, mentors and former #ESoWC participants.
➡️[Sign up](https://esowc.ecmwf.int/ama)

**Comment by jwagemann** [comment]
Only 4 days left to apply to be part of ECMWF Summer of Weather Code 2020. 
Application deadline: **Wednesday, 22 April 2020 at 23:59 (BST)**. 
Submit your proposal [here](https://esowc.commpla.com/form/application-form).
